import type { NextPage } from "next";
import Head from "next/head";
import Container from "@/design_systems/mainds/components/Container";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container type="screen-sm">
          <div style={{ margin: "128px auto" }}>
            <p>Default template removed.</p>
          </div>
        </Container>
      </main>
    </div>
  );
};

export default Home;
